<?php

namespace Noxlogic\PhpotonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{

    function count() {
        $query = $this->createQueryBuilder('q')
            ->select('COUNT(q.id)')
            ->getQuery();
        return $query->getSingleScalarResult();
    }

    /**
     * @return Question
     */
    function random() {
        // F*& it, dql can't be registered from config.yml, and no time to figure out why
        $this->getEntityManager()->getConfiguration()->addCustomNumericFunction('RAND', 'Noxlogic\PhpotonBundle\Doctrine\Rand');

        $query = $this->createQueryBuilder('q')
            ->addSelect('RAND() as HIDDEN rand')
            ->orderBy('rand')
            ->setMaxResults(1)
            ->getQuery();
        return $query->getSingleResult();
    }

}
